services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"  # Mapeando a porta 8080 do container para a porta 80 da máquina local
    restart: always
    environment:
      - MAP_INITIAL_COORDS=${MAP_INITIAL_COORDS}
